language: node_js
node_js:
  - "10"
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g codecov
  - npm install -g jest
  - npm install -g mocha
#  - npm install jest-puppeteer puppeteer
before_script:
  - npm la

#script:
#  - jest
#  - codecov