language: node_js
node_js:
  - "10"
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - node --version
  - npm --version
  - npx --version
  - npm install -g codecov
  - npm install -g jest
  - npm install -g mocha
before_script:
  - node --version
  - npm --version
  - npx --version
after_script:
  - codecov
