language: node_js
node_js:
  - "10"
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - npm install -g codecov
  - npm install -g istanbul
script:
  - istanbul cover ./node_modules/mocha/bin/mocha --reporter lcovonly -- -R spec
  - codecov